import { ProductionOrderType } from "./types";

export const mockOrders: ProductionOrderType[] = [
  {
    id: 1,
    orderCode: "ORD-001",
    operation: "Spot Welding",
    quantity: 120,
    deadline: "2025-06-15",
    priority: "High",
  },
  {
    id: 2,
    orderCode: "ORD-002",
    operation: "Riveting",
    quantity: 80,
    deadline: "2025-06-16",
    priority: "Medium",
  },
  {
    id: 3,
    orderCode: "ORD-003",
    operation: "Painting",
    quantity: 200,
    deadline: "2025-06-14",
    priority: "Low",
  },
  {
    id: 4,
    orderCode: "ORD-004",
    operation: "Spot Welding",
    quantity: 120,
    deadline: "2025-06-15",
    priority: "High",
  },
  {
    id: 5,
    orderCode: "ORD-005",
    operation: "Riveting",
    quantity: 80,
    deadline: "2025-06-16",
    priority: "Medium",
  },
  {
    id: 6,
    orderCode: "ORD-006",
    operation: "Painting",
    quantity: 200,
    deadline: "2025-06-14",
    priority: "Low",
  },
  {
    id: 7,
    orderCode: "FAB-006",
    operation: "Painting",
    quantity: 200,
    deadline: "2025-06-14",
    priority: "Low",
  },
];
